import type {
  CompletionRequest,
  CompletionResponse,
  ModelProvider,
  ProviderInfo,
} from './types.js'

/**
 * MockProvider runs fully offline. It exists so the MVP can demonstrate
 * the full chat → permission → tool → audit flow without any cloud key.
 * It uses keyword heuristics, not an actual model.
 */
export class MockProvider implements ModelProvider {
  info: ProviderInfo = {
    id: 'mock',
    label: 'Local Mock (offline)',
    local: true,
    dataSentNotice:
      'Nothing leaves this machine. Responses are generated by simple local heuristics.',
  }

  async complete(req: CompletionRequest): Promise<CompletionResponse> {
    const last = req.messages[req.messages.length - 1]?.content?.trim() ?? ''
    const lower = last.toLowerCase()

    if (/\b(pending|missed|reply|chuta|jawab|forgot)\b/.test(lower)) {
      return {
        text:
          "Looking at your inbox and threads for messages that look pending. " +
          "I'll need your confirmation before sending any draft reply.",
        suggestedTool: {
          toolName: 'pending.scan',
          input: { kinds: ['email', 'whatsapp'] },
          rationale:
            'You asked about missed replies. Scanning connected accounts to surface threads that look pending.',
        },
      }
    }
    if (/\b(remember|yaad rakh|save|note)\b/.test(lower)) {
      return {
        text:
          "I can save that as a memory. Use the Memory page to confirm or " +
          "edit before I keep it. I will not store secrets, OTPs or payment info.",
      }
    }
    if (/\b(read|inbox|email|gmail)\b/.test(lower)) {
      return {
        text:
          "Email reading requires the Email connector and the email.read permission. " +
          "Open the Connectors and Permissions screens to enable them.",
      }
    }
    return {
      text:
        "I'm running in local mock mode. I can plan and explain actions, but " +
        "I won't perform anything without your confirmation. Try asking about " +
        "pending replies, memory, or setting up a connector.",
    }
  }
}
